local a = {
["1"] = {
   id = "1",
   prepath = "sound/bomb_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["2"] = {
   id = "2",
   prepath = "sound/bomb_02.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["3"] = {
   id = "3",
   prepath = "sound/bomb_03.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["4"] = {
   id = "4",
   prepath = "sound/bombdown_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["5"] = {
   id = "5",
   prepath = "sound/bossalert_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["6"] = {
   id = "6",
   prepath = "sound/capture_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["7"] = {
   id = "7",
   prepath = "sound/collect_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["8"] = {
   id = "8",
   prepath = "sound/com_btn01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["9"] = {
   id = "9",
   prepath = "sound/com_btn02.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["10"] = {
   id = "10",
   prepath = "sound/com_btn03.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["11"] = {
   id = "11",
   prepath = "sound/com_btn04.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["12"] = {
   id = "12",
   prepath = "sound/congrat_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["13"] = {
   id = "13",
   prepath = "sound/exit_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["14"] = {
   id = "14",
   prepath = "sound/fishdead_002.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["15"] = {
   id = "15",
   prepath = "sound/fishdead_003.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["16"] = {
   id = "16",
   prepath = "sound/fishdead_004.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["17"] = {
   id = "17",
   prepath = "sound/fishdead_005.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["18"] = {
   id = "18",
   prepath = "sound/fishdead_006.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["19"] = {
   id = "19",
   prepath = "sound/fishdead_007.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["20"] = {
   id = "20",
   prepath = "sound/fishdead_008.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["21"] = {
   id = "21",
   prepath = "sound/fishdead_009.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["22"] = {
   id = "22",
   prepath = "sound/fishdead_010.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["23"] = {
   id = "23",
   prepath = "sound/fishdead_011.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["24"] = {
   id = "24",
   prepath = "sound/fishdead_012.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["25"] = {
   id = "25",
   prepath = "sound/fishfreeze_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["26"] = {
   id = "26",
   prepath = "sound/forged_fail.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["27"] = {
   id = "27",
   prepath = "sound/forged_forgeding.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["28"] = {
   id = "28",
   prepath = "sound/forged_success.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["29"] = {
   id = "29",
   prepath = "sound/getprop_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["30"] = {
   id = "30",
   prepath = "sound/getprop_02.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["31"] = {
   id = "31",
   prepath = "sound/gold_get01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["32"] = {
   id = "32",
   prepath = "sound/gold_get02.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["33"] = {
   id = "33",
   prepath = "sound/gunfire_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["34"] = {
   id = "34",
   prepath = "sound/gunswitch_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["35"] = {
   id = "35",
   prepath = "sound/hourglass_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["36"] = {
   id = "36",
   prepath = "sound/lightning_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["37"] = {
   id = "37",
   prepath = "sound/lock_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["38"] = {
   id = "38",
   prepath = "sound/lvup_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["39"] = {
   id = "39",
   prepath = "sound/magicprop01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["40"] = {
   id = "40",
   prepath = "sound/magicprop02.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["41"] = {
   id = "41",
   prepath = "sound/magicprop03.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["42"] = {
   id = "42",
   prepath = "sound/magicprop04.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["43"] = {
   id = "43",
   prepath = "sound/magicprop05.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["44"] = {
   id = "44",
   prepath = "sound/music_fishgroup.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["45"] = {
   id = "45",
   prepath = "sound/readygo_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["46"] = {
   id = "46",
   prepath = "sound/readygo_02.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["47"] = {
   id = "47",
   prepath = "sound/rolling_01.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["48"] = {
   id = "48",
   prepath = "sound/rolling_02.mp3",
   loadtype = "effect",
   NULL = "",
   NULL = "",
   },
["49"] = {
   id = "49",
   prepath = "sound/music_bosscome.mp3",
   loadtype = "music",
   NULL = "",
   NULL = "",
   },
["50"] = {
   id = "50",
   prepath = "sound/music_001.mp3",
   loadtype = "music",
   NULL = "",
   NULL = "",
   },
["51"] = {
   id = "51",
   prepath = "sound/music_002.mp3",
   loadtype = "music",
   NULL = "",
   NULL = "",
   },
["52"] = {
   id = "52",
   prepath = "sound/music_003.mp3",
   loadtype = "music",
   NULL = "",
   NULL = "",
   },
["53"] = {
   id = "53",
   prepath = "sound/music_004.mp3",
   loadtype = "music",
   NULL = "",
   NULL = "",
   },
["54"] = {
   id = "54",
   prepath = "sound/music_005.mp3",
   loadtype = "music",
   NULL = "",
   NULL = "",
   },
["55"] = {
   id = "55",
   prepath = "sound/music_bg.mp3",
   loadtype = "music",
   NULL = "",
   NULL = "",
   },
["56"] = {
   id = "56",
   prepath = "fish/plist/fishid1",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["57"] = {
   id = "57",
   prepath = "fish/plist/fishid2",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["58"] = {
   id = "58",
   prepath = "fish/plist/fishid3",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["59"] = {
   id = "59",
   prepath = "fish/plist/fishid4",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["60"] = {
   id = "60",
   prepath = "fish/plist/fishid5",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["61"] = {
   id = "61",
   prepath = "fish/plist/fishid6",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["62"] = {
   id = "62",
   prepath = "fish/plist/fishid7",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["63"] = {
   id = "63",
   prepath = "fish/plist/fishid8",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["64"] = {
   id = "64",
   prepath = "fish/plist/fishid9",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["65"] = {
   id = "65",
   prepath = "fish/plist/fishid10",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["66"] = {
   id = "66",
   prepath = "fish/plist/fishid11",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["67"] = {
   id = "67",
   prepath = "fish/plist/fishid12",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["68"] = {
   id = "68",
   prepath = "fish/plist/fishid13",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["69"] = {
   id = "69",
   prepath = "fish/plist/fishid14",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["70"] = {
   id = "70",
   prepath = "fish/plist/fishid15",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["71"] = {
   id = "71",
   prepath = "fish/plist/fishid16",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["72"] = {
   id = "72",
   prepath = "fish/plist/fishid50",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["73"] = {
   id = "73",
   prepath = "fish/plist/fishid51",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["74"] = {
   id = "74",
   prepath = "fish/plist/fishid52",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["75"] = {
   id = "75",
   prepath = "fish/plist/fishid53",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["76"] = {
   id = "76",
   prepath = "fish/plist/fishid101",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["77"] = {
   id = "77",
   prepath = "fish/plist/fishid102",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["78"] = {
   id = "78",
   prepath = "fish/plist/fishid103",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["79"] = {
   id = "79",
   prepath = "fish/plist/fishid104",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["80"] = {
   id = "80",
   prepath = "fish/plist/fishid105",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["81"] = {
   id = "81",
   prepath = "fish/plist/fishid151",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["82"] = {
   id = "82",
   prepath = "fish/plist/fishid152",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["83"] = {
   id = "83",
   prepath = "fish/plist/fishid153",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["84"] = {
   id = "84",
   prepath = "fish/plist/fishid154",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["85"] = {
   id = "85",
   prepath = "fish/plist/fishid155",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["86"] = {
   id = "86",
   prepath = "fish/plist/fishid156",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["87"] = {
   id = "87",
   prepath = "fish/plist/fishid157",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["88"] = {
   id = "88",
   prepath = "fish/plist/fishid158",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["89"] = {
   id = "89",
   prepath = "fish/plist/fishid201",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["90"] = {
   id = "90",
   prepath = "fish/plist/fishid204",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["91"] = {
   id = "91",
   prepath = "fish/plist/fishid501",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["92"] = {
   id = "92",
   prepath = "common/coin/game_coin2",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["93"] = {
   id = "93",
   prepath = "common/coin/friend_coin2",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["94"] = {
   id = "94",
   prepath = "common/coin/game_coin1",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["95"] = {
   id = "95",
   prepath = "common/coin/friend_coin1",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["96"] = {
   id = "96",
   prepath = "battle/effect/net_1",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["97"] = {
   id = "97",
   prepath = "battle/effect/net_2",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["98"] = {
   id = "98",
   prepath = "battle/effect/net_3",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["99"] = {
   id = "99",
   prepath = "battle/effect/net_4",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["100"] = {
   id = "100",
   prepath = "battle/effect/net_5",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["101"] = {
   id = "101",
   prepath = "battle/effect/net_6",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["102"] = {
   id = "102",
   prepath = "battle/effect/net_7",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["103"] = {
   id = "103",
   prepath = "battle/effect/net_8",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["104"] = {
   id = "104",
   prepath = "battle/effect/net_9",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["105"] = {
   id = "105",
   prepath = "battle/effect/net_10",
   loadtype = "plist",
   NULL = "",
   NULL = "",
   },
["106"] = {
   id = "106",
   prepath = "battle/effect/blast1_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["107"] = {
   id = "107",
   prepath = "battle/effect/blast1_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["108"] = {
   id = "108",
   prepath = "battle/effect/blast1_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["109"] = {
   id = "109",
   prepath = "battle/effect/blast1_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["110"] = {
   id = "110",
   prepath = "battle/effect/blast1_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["111"] = {
   id = "111",
   prepath = "battle/effect/blast1_05",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["112"] = {
   id = "112",
   prepath = "battle/effect/blast1_06",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["113"] = {
   id = "113",
   prepath = "battle/effect/blast1_07",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["114"] = {
   id = "114",
   prepath = "battle/effect/blast1_08",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["115"] = {
   id = "115",
   prepath = "battle/effect/blast2_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["116"] = {
   id = "116",
   prepath = "battle/effect/blast2_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["117"] = {
   id = "117",
   prepath = "battle/effect/blast2_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["118"] = {
   id = "118",
   prepath = "battle/effect/blast2_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["119"] = {
   id = "119",
   prepath = "battle/effect/blast2_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["120"] = {
   id = "120",
   prepath = "battle/effect/blast2_05",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["121"] = {
   id = "121",
   prepath = "battle/effect/blast2_06",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["122"] = {
   id = "122",
   prepath = "battle/effect/blast2_07",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["123"] = {
   id = "123",
   prepath = "battle/effect/blast2_08",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["124"] = {
   id = "124",
   prepath = "battle/effect/blast3",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["125"] = {
   id = "125",
   prepath = "battle/effect/net_1_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["126"] = {
   id = "126",
   prepath = "battle/effect/net_1_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["127"] = {
   id = "127",
   prepath = "battle/effect/net_1_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["128"] = {
   id = "128",
   prepath = "battle/effect/net_1_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["129"] = {
   id = "129",
   prepath = "battle/effect/net_1_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["130"] = {
   id = "130",
   prepath = "battle/effect/net_1_05",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["131"] = {
   id = "131",
   prepath = "battle/effect/net_1_06",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["132"] = {
   id = "132",
   prepath = "battle/effect/net_1_07",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["133"] = {
   id = "133",
   prepath = "battle/effect/net_1_08",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["134"] = {
   id = "134",
   prepath = "battle/effect/net_1_09",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["135"] = {
   id = "135",
   prepath = "battle/effect/gunfire_1_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["136"] = {
   id = "136",
   prepath = "battle/effect/gunfire_1_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["137"] = {
   id = "137",
   prepath = "battle/effect/gunfire_1_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["138"] = {
   id = "138",
   prepath = "battle/effect/gunfire_1_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["139"] = {
   id = "139",
   prepath = "battle/effect/gunfire_1_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["140"] = {
   id = "140",
   prepath = "battle/effect/fl_blast2_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["141"] = {
   id = "141",
   prepath = "battle/effect/fl_blast2_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["142"] = {
   id = "142",
   prepath = "battle/effect/fl_blast2_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["143"] = {
   id = "143",
   prepath = "battle/effect/fl_blast2_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["144"] = {
   id = "144",
   prepath = "battle/effect/fl_blast2_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["145"] = {
   id = "145",
   prepath = "battle/effect/fl_blast2_05",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["146"] = {
   id = "146",
   prepath = "battle/effect/fl_blast2_06",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["147"] = {
   id = "147",
   prepath = "battle/effect/fl_blast2_07",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["148"] = {
   id = "148",
   prepath = "battle/effect/fl_blast2_08",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["149"] = {
   id = "149",
   prepath = "battle/effect/boomeffect01_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["150"] = {
   id = "150",
   prepath = "battle/effect/boomeffect01_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["151"] = {
   id = "151",
   prepath = "battle/effect/boomeffect01_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["152"] = {
   id = "152",
   prepath = "battle/effect/boomeffect01_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["153"] = {
   id = "153",
   prepath = "battle/effect/boomeffect01_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["154"] = {
   id = "154",
   prepath = "battle/effect/boomeffect01_05",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["155"] = {
   id = "155",
   prepath = "battle/effect/boomeffect01_06",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["156"] = {
   id = "156",
   prepath = "battle/effect/boomeffect01_07",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["157"] = {
   id = "157",
   prepath = "battle/effect/boomeffect01_08",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["158"] = {
   id = "158",
   prepath = "battle/killbonus/bonus_wheel_bg",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["159"] = {
   id = "159",
   prepath = "battle/killbonus/bonus_wheel_title_bg",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["160"] = {
   id = "160",
   prepath = "battle/effect/boomeffect02_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["161"] = {
   id = "161",
   prepath = "battle/effect/boomeffect02_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["162"] = {
   id = "162",
   prepath = "battle/effect/boomeffect03_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["163"] = {
   id = "163",
   prepath = "battle/effect/boomeffect03_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["164"] = {
   id = "164",
   prepath = "battle/effect/boomeffect04_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["165"] = {
   id = "165",
   prepath = "battle/effect/boomeffect04_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["166"] = {
   id = "166",
   prepath = "battle/effect/boomeffect04_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["167"] = {
   id = "167",
   prepath = "battle/effect/boomeffect04_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["168"] = {
   id = "168",
   prepath = "battle/effect/boomeffect04_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["169"] = {
   id = "169",
   prepath = "battle/effect/boomeffect04_05",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["170"] = {
   id = "170",
   prepath = "battle/effect/boomeffect04_06",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["171"] = {
   id = "171",
   prepath = "battle/effect/boomeffect04_07",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["172"] = {
   id = "172",
   prepath = "battle/effect/boomeffect04_08",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["173"] = {
   id = "173",
   prepath = "battle/effect/boomeffect04_09",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["174"] = {
   id = "174",
   prepath = "battle/effect/boomeffect05_00",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["175"] = {
   id = "175",
   prepath = "battle/effect/boomeffect05_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["176"] = {
   id = "176",
   prepath = "battle/effect/boomeffect05_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["177"] = {
   id = "177",
   prepath = "battle/effect/boomeffect05_03",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["178"] = {
   id = "178",
   prepath = "battle/effect/boomeffect05_04",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["179"] = {
   id = "179",
   prepath = "battle/effect/boomeffect05_05",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["180"] = {
   id = "180",
   prepath = "battle/effect/boomeffect05_06",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["181"] = {
   id = "181",
   prepath = "battle/effect/boomeffect05_07",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["182"] = {
   id = "182",
   prepath = "battle/effect/boomeffect05_08",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["183"] = {
   id = "183",
   prepath = "battle/effect/effect_lamp_clouds",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["184"] = {
   id = "184",
   prepath = "battle/effect/effect_skll_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["185"] = {
   id = "185",
   prepath = "battle/nuclear/nuclear_pic_bomb",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["186"] = {
   id = "186",
   prepath = "battle/nuclear/nuclear_pic_plane",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["187"] = {
   id = "187",
   prepath = "battle/nuclear/nuclear_pic_range",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["188"] = {
   id = "188",
   prepath = "battle/nuclear/nuclear_pic_range_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["189"] = {
   id = "189",
   prepath = "battle/nuclear/nuclear_pic_range_02",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["190"] = {
   id = "190",
   prepath = "battle/nuclear/nuclear_pic_sight",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["191"] = {
   id = "191",
   prepath = "battle/nuclear/nuclear_pic_sight_01",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["192"] = {
   id = "192",
   prepath = "battle/nuclear/nuclear_tips",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["193"] = {
   id = "193",
   prepath = "battle/nuclear/nuclear_tips_1",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["194"] = {
   id = "194",
   prepath = "battle/nuclear/nuclear_tips_2",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["195"] = {
   id = "195",
   prepath = "battle/hourglass/hourglass_bg_1",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["196"] = {
   id = "196",
   prepath = "battle/hourglass/hourglass_bg_2",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["197"] = {
   id = "197",
   prepath = "battle/hourglass/hourglass_bg_3",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["198"] = {
   id = "198",
   prepath = "battle/hourglass/hourglass_bg_4",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["199"] = {
   id = "199",
   prepath = "battle/hourglass/hourglass_bg_5",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["200"] = {
   id = "200",
   prepath = "battle/hourglass/hourglass_bg_6",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["201"] = {
   id = "201",
   prepath = "battle/hourglass/hourglass_bg_7",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["202"] = {
   id = "202",
   prepath = "battle/hourglass/hourglass_big",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["203"] = {
   id = "203",
   prepath = "battle/hourglass/hourglass_buff",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["204"] = {
   id = "204",
   prepath = "battle/hourglass/hourglass_pic_hsyb",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["205"] = {
   id = "205",
   prepath = "battle/hourglass/hourglass_pic_ksjs",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["206"] = {
   id = "206",
   prepath = "battle/hourglass/hourglass_skill_animation_1",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["207"] = {
   id = "207",
   prepath = "battle/hourglass/hourglass_skill_animation_2",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["208"] = {
   id = "208",
   prepath = "battle/hourglass/hourglass_text_s",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["209"] = {
   id = "209",
   prepath = "common/layerbg/com_bg_pic_1",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["210"] = {
   id = "210",
   prepath = "common/layerbg/com_bg_pic_2",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["211"] = {
   id = "211",
   prepath = "common/layerbg/com_bg_pic_3",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["212"] = {
   id = "212",
   prepath = "common/layerbg/com_bg_pic_tmbg",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["213"] = {
   id = "213",
   prepath = "common/layerbg/com_bg_pic_bsbg",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["214"] = {
   id = "214",
   prepath = "common/layerbg/com_bg_item_info",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["215"] = {
   id = "215",
   prepath = "common/layerbg/com_bg_pic_zsbg",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["216"] = {
   id = "216",
   prepath = "common/layerbg/com_pic_minbg",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["217"] = {
   id = "217",
   prepath = "common/btn/com_btn_red_0",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["218"] = {
   id = "218",
   prepath = "common/btn/com_btn_red_1",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["219"] = {
   id = "219",
   prepath = "common/btn/com_btn_green_0",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["220"] = {
   id = "220",
   prepath = "common/btn/com_btn_green_1",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["221"] = {
   id = "221",
   prepath = "common/com_pic_hookbg",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["222"] = {
   id = "222",
   prepath = "common/com_pic_hook",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["223"] = {
   id = "223",
   prepath = "battle/bosscome/title_pic_152",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["224"] = {
   id = "224",
   prepath = "battle/bosscome/title_pic_153",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["225"] = {
   id = "225",
   prepath = "battle/bosscome/title_pic_154",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["226"] = {
   id = "226",
   prepath = "battle/bosscome/title_pic_155",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["227"] = {
   id = "227",
   prepath = "battle/bosscome/title_pic_156",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["228"] = {
   id = "228",
   prepath = "battle/bosscome/title_pic_157",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["229"] = {
   id = "229",
   prepath = "battle/bosscome/title_pic_158",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
["230"] = {
   id = "230",
   prepath = "common/com_pic_photo_1",
   loadtype = "png",
   NULL = "",
   NULL = "",
   },
}
return a
